# Generated by Django 5.1 on 2024-08-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='provider_type',
            field=models.CharField(blank=True, choices=[('Alojamiento', 'Alojamiento'), ('Venue', 'Venue'), ('Restaurante/Catering', 'Restaurante/Catering'), ('Actividades', 'Proveedor de Actividades'), ('Entretenimiento', 'Proveedor de Entretenimiento'), ('Decoración', 'Proveedor de Decoración')], max_length=50, null=True),
        ),
    ]
